Update BicepCompilerToARMTemplate.yml

diff --git a/.github/workflows/BicepCompilerToARMTemplate.yml b/.github/workflows/BicepCompilerToARMTemplate.yml
--- a/.github/workflows/BicepCompilerToARMTemplate.yml
+++ b/.github/workflows/BicepCompilerToARMTemplate.yml
@@ -23,15 +23,28 @@ jobs:
           sudo apt-get update && sudo apt-get install -y azure-cli
 
       - name: Compile Bicep to ARM template (JSON)
-        run: |
-          az bicep build --file ${BICEP_FILE_NAME}.bicep --outfile ${BICEP_FILE_NAME}.json
-          if [ ! -f ${BICEP_FILE_NAME}.json ]; then
-            echo "Failed to generate JSON file"
-            exit 1
-          fi
+        run: az bicep build --file "Create_RG_in_Azure/ResourceGroup.bicep" --outfile "Create_RG_in_Azure/ResourceGroup.json"
+        #run: |
+        #  az bicep build --file ${BICEP_FILE_NAME}.bicep --outfile ${BICEP_FILE_NAME}.json
+        #  if [ ! -f ${BICEP_FILE_NAME}.json ]; then
+        #    echo "Failed to generate JSON file"
+        #    exit 1
+        #  fi
 
       - name: Commit JSON file
         uses: EndBug/add-and-commit@v7
         with:
           message: "Add generated ARM template JSON file"
           add: "${BICEP_FILE_NAME}.json"
+          
+      - name: Commit changes
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: "Build Bicep file"
+
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: main
+          directory: "."
+          github_token: ${{ secrets.GITHUB_TOKEN }}
