Update Workflow8.yml

diff --git a/.github/workflows/Workflow8.yml b/.github/workflows/Workflow8.yml
--- a/.github/workflows/Workflow8.yml
+++ b/.github/workflows/Workflow8.yml
@@ -23,7 +23,12 @@ jobs:
             az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
       - name: Compile Bicep to ARM template (JSON)
-        run: az bicep build --file ${{ env.BICEP_FILE_NAME }}.bicep --outfile ${{ env.BICEP_FILE_NAME }}.json
+        run: | 
+          az bicep build --file ${{ env.BICEP_FILE_NAME }}.bicep --outfile ${{ env.BICEP_FILE_NAME }}.json
+          if [ ! -f ${{ env.BICEP_FILE_NAME }}.json ]; then
+            echo "Failed to generate JSON file"
+            exit 1
+          fi
 
       - name: Create Resource Group
         run: az deployment sub create --name RGAttempt1 --location eastus --template-uri https://raw.githubusercontent.com/SN705/Create_RG_in_Azure/main/ResourceGroup.json
